-module(help_integration_tests).

-include_lib("eunit/include/eunit.hrl").

-include("integration_tests_defs.hrl").

integration_test_() ->
    integration_tests_common:create_tests_entry([
        {"help: show all commands for user at fundamental mode",
         ["guest", "idclip", "?logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>?", "logout\tshow vlan\tping"] ++ ?GUEST_LOGOUT},
        {"help: show all commands for admin at fundamental mode",
         ["root", "iddqd", "?logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#?", "logout\tconfigure terminal\tshow vlan\tping"] ++ ?ADMIN_LOGOUT},
        {"help: show all commands for admin at global configuration mode",
         ["root", "iddqd", "c t", "?end", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, ?CONFIG_TERM_SHORTCUT, "root@CliDemo (config)#?", "no vlan\tend\texit\tinterface range\tinterface\tvlan\tshow vlan"] ++ ?CONFIG_LOGOUT},
        {"help: show commands started with p for user at fundamental mode",
         ["guest", "idclip", "p?logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>p?", "ping"] ++ ?GUEST_LOGOUT},
        {"help: show commands started with p for admin at fundamental mode",
         ["root", "iddqd", "p?logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#p?", "ping"] ++ ?ADMIN_LOGOUT},
        {"help: show commands started with c for admin at fundamental mode",
         ["root", "iddqd", "c?logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#c?", "configure terminal"] ++ ?ADMIN_LOGOUT},
        {"help: show commands started with i for admin at global configuration mode",
         ["root", "iddqd", "c t", "i?end", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, ?CONFIG_TERM_SHORTCUT, "root@CliDemo (config)#i?", "interface range\tinterface"] ++ ?CONFIG_LOGOUT},
        {"help: show commands for unknown command for user at fundamental mode",
         ["guest", "idclip", "x?", "logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>x", ?UNKNOWN_COMMAND] ++ ?GUEST_LOGOUT},
        {"help: show commands for unknown command for admin at fundamental mode",
         ["root", "iddqd", "x?", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#x", ?UNKNOWN_COMMAND] ++ ?ADMIN_LOGOUT},
        {"help: show commands for unsuitable command for user at fundamental mode",
         ["guest", "idclip", "end?", "logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>end", ?ACCESS_DENIED, ?COMMAND_FAIL] ++ ?GUEST_LOGOUT},
        {"help: show commands for unsuitable command for admin at fundamental mode",
         ["root", "iddqd", "end?", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#end", ?UNSUITABLE_COMMAND, ?COMMAND_FAIL] ++ ?ADMIN_LOGOUT},
        {"help: show help for ping for user at fundamental mode",
         ["guest", "idclip", "ping ?logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>ping ?", "ping ... command help"] ++ ?GUEST_LOGOUT},
        {"help: show help for p for user at fundamental mode",
         ["guest", "idclip", "p ?logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>p ?", "ping ... command help"] ++ ?GUEST_LOGOUT},
        {"help: show help for ping for admin at fundamental mode",
         ["root", "iddqd", "ping ?logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#ping ?", "ping ... command help"] ++ ?ADMIN_LOGOUT},
        {"help: show help for p for admin at fundamental mode",
         ["root", "iddqd", "p ?logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#p ?", "ping ... command help"] ++ ?ADMIN_LOGOUT},
        {"help: show help for unknown command for user at fundamental mode",
         ["guest", "idclip", "pong ?", "logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>pong ", ?UNKNOWN_COMMAND] ++ ?GUEST_LOGOUT},
        {"help: show help for unknown command for admin at fundamental mode",
         ["root", "iddqd", "pong ?", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#pong ", ?UNKNOWN_COMMAND] ++ ?ADMIN_LOGOUT},
        {"help: show help for unsuitable command for user at fundamental mode",
         ["guest", "idclip", "end ?", "logout"],
         ?GUEST_LOGIN ++ [?GREETING, "guest@CliDemo>end ", ?ACCESS_DENIED, ?COMMAND_FAIL] ++ ?GUEST_LOGOUT},
        {"help: show help for unsuitable command for admin at fundamental mode",
         ["root", "iddqd", "end ?", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, "root@CliDemo#end ", ?UNSUITABLE_COMMAND, ?COMMAND_FAIL] ++ ?ADMIN_LOGOUT},
        {"help: show help for ambiguous command for admin at global configuration mode",
         ["root", "iddqd", "c t", "e ?", "end", "logout"],
         ?ADMIN_LOGIN ++ [?GREETING, ?CONFIG_TERM_SHORTCUT, "root@CliDemo (config)#e ", ?UNKNOWN_COMMAND] ++ ?CONFIG_LOGOUT}]).