-module(transition_integration_tests).

-include_lib("eunit/include/eunit.hrl").

-include("integration_tests_defs.hrl").

integration_test_() ->
    integration_tests_common:create_tests_entry([
        {["login", "root", "iddqd", "no name", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#" ++ ?UNSUITABLE_COMMAND, ?COMMAND_FAIL, ?ADMIN_LOGOUT],
         "transition: execute unsuitable command"},
        {["login", "root", "iddqd", "configure terminal", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#You are logged out."],
         "transition: enter into global configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "interface someinterface 0/1", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if)#You are logged out."],
         "transition: enter into interface configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "interface range someinterface 0/1,3-5", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if-range)#You are logged out."],
         "transition: enter into interface range configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "vlan 666", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-vlan)#You are logged out."],
         "transition: enter into vlan configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "interface someinterface 0/1", "exit", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if)#root@CliDemo (config)#You are logged out."],
         "transition: exit from interface configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "interface range someinterface 0/1,3-5", "exit", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if-range)#root@CliDemo (config)#You are logged out."],
         "transition: exit from interface range configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "vlan 666", "exit", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-vlan)#root@CliDemo (config)#You are logged out."],
         "transition: exit from vlan configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "exit", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo#You are logged out."],
         "transition: exit from global configuration mode"},
        {["login", "root", "iddqd", "exit", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#" ++ ?UNSUITABLE_COMMAND, ?COMMAND_FAIL, ?ADMIN_LOGOUT],
         "transition: exit from fundamental mode"},
        {["login", "root", "iddqd", "configure terminal", "interface someinterface 0/1", "end", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if)#root@CliDemo#You are logged out."],
         "transition: end interface configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "interface range someinterface 0/1,3-5", "end", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-if-range)#root@CliDemo#You are logged out."],
         "transition: end interface range configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "vlan 666", "end", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo (config-vlan)#root@CliDemo#You are logged out."],
         "transition: end vlan configuration mode"},
        {["login", "root", "iddqd", "configure terminal", "end", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#root@CliDemo (config)#root@CliDemo#You are logged out."],
         "transition: end global configuration mode"},
        {["login", "root", "iddqd", "end", "logout"],
         [?LOGIN, ?GREETING, "root@CliDemo#" ++ ?UNSUITABLE_COMMAND, ?COMMAND_FAIL, ?ADMIN_LOGOUT],
         "transition: end fundamental mode"}]).